version: '3.9'

services:
  nginx:
    container_name: nginx
    build: ./nginx
    ports:
      - 80:80
    depends_on:
      - api

  api:
    container_name: api
    build: 
      context: api/. 
    ports:
      - 8080:8080
    command: ["go", "run", "main.go"]
